name: Demystifier PR Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build for PR"
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        config: [Debug, Release]
    steps:
      - name: Clone source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK (v2.1)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.1.818'
      - name: Setup .NET SDK (v3.1)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.414'
      - name: Setup .NET SDK (v5.0)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.402'
      - name: Setup .NET SDK (v6.0)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.417'

      - name: Get .NET information
        run: dotnet --info

      - name: Build
        run: dotnet build -c ${{ matrix.config }}
      
      - name: "Test"
        run: dotnet test -c ${{ matrix.config }}
        
