name: Demystifier PR Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build for PR"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        config: [Debug, Release]
    steps:
      - name: Clone source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          echo "DOTNET_NOLOGO=true" >> $GITHUB_ENV

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: |
                9.0.100

      - name: Get .NET information
        run: dotnet --info

      - name: Build
        run: dotnet build -c ${{ matrix.config }}
      
      - name: "Test"
        run: dotnet test -c ${{ matrix.config }} -l "trx;LogFilePrefix=testresults_${{ runner.os }}_${{ matrix.config }}"

      - name: "Upload Test Results"
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: test-results-${{ runner.os }}-${{ matrix.config }}.trx
            path: '**/testresults_*.trx'        
